apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: aks-app
        image: notts01.azurecr.io/aks-app:latest  # Replace <new-tag> with the latest tag
        ports:
        - containerPort: 8081