trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'notts01'
  aksResourceGroup: 'my-resource-group'
  aksClusterName: 'my-aks-cluster'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(acrName)'
        repository: 'aks-app'
        command: 'buildAndPush'
        Dockerfile: 'docker/Dockerfile'
        tags: $(Build.BuildId)

- stage: Deploy
  jobs:
  - deployment: DeployToAKS
    environment: 'aks-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Crayon-Conn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName)
                kubectl apply -f manifests/k8s-deployment.yaml
