trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'notts01'                    # Replace with your actual ACR name
  imageRepository: 'aks-app'            # Name of the repository in ACR
  clientId: '<your-client-id>'          # Service Principal Client ID
  clientSecret: '<your-client-secret>'  # Service Principal Client Secret
  tenantId: '<your-tenant-id>'          # Tenant ID for the Service Principal

stages:
- stage: Build
  displayName: 'Build and Push to ACR'
  jobs:
  - job: BuildAndPush
    displayName: 'Build Docker image and push to ACR'
    steps:
    - script: |
        # Print the current working directory and its contents
        echo "Current working directory:"
        pwd
        echo "Contents of the current directory:"
        ls -al

        # List contents of the directory one level up as well
        echo "Contents of the parent directory:"
        ls -al ..

        # Log in to Azure and then ACR
        az login --service-principal -u $(clientId) -p $(clientSecret) --tenant $(tenantId)
        az acr login --name $(acrName)

        # Attempt to build the Docker image with different build contexts based on output
        docker build -f docker/Dockerfile -t $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId) ./src || \
        docker build -f docker/Dockerfile -t $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId) ../src || \
        docker build -f docker/Dockerfile -t $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId) .

        # Verify that the image exists locally
        echo "Listing Docker images to confirm tagging"
        docker images | grep $(imageRepository)
      displayName: 'Build Docker Image'
      env:
        clientId: $(clientId)
        clientSecret: $(clientSecret)
        tenantId: $(tenantId)

    - script: |
        docker login $(acrName).azurecr.io -u $(clientId) -p $(clientSecret)
        docker push $(acrName).azurecr.io/$(imageRepository):$(Build.BuildId)
      displayName: 'Push Docker Image to ACR'
      condition: succeeded()  # Only push if the build step succeeds
