apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: aks-app
        image: notts01.azurecr.io/aks-app:$(Build.BuildId)
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aks-app-service
spec:
  selector:
    app: aks-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
