apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: aks-app
  template:
    metadata:
      labels:
        app: aks-app
    spec:
      containers:
      - name: aks-app
        image: notts01.azurecr.io/aks-app:latest
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acr-secret  # Reference the secret created above