# Voting App Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote:latest
        ports:
        - containerPort: 80  # Ensure internal port remains 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: voting
  ports:
  - protocol: TCP
    port: 80         # External port set to 80
    targetPort: 80   # Internal port matches container port
  type: LoadBalancer