# Voting App Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
    spec:
      containers:
      - name: vote
        image: dockersamples/examplevotingapp_vote:latest
        ports:
        - containerPort: 8080  # Changed to 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    app: voting
  ports:
  - protocol: TCP
    port: 80              # External port on the LoadBalancer (can stay 80 if desired)
    targetPort: 8080      # Internal port to route traffic to (matches containerPort)
  type: LoadBalancer
---
# Redis Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
