trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'azureSubscription'
    value: 'your-azure-subscription'  # This should match your Azure DevOps service connection

steps:
# Step 1: Install Terraform
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

# Step 2: Terraform Initialization
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'AzureDevOpsServiceConnection'  # Replace this with your service connection name
    backendAzureRmResourceGroupName: 'myStorageResourceGroup'
    backendAzureRmStorageAccountName: 'mystorageaccount'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'aks-cluster/terraform.tfstate'

# Step 3: Terraform Plan using tfvars file
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'  # Adjust path if necessary
    commandOptions: '-var-file="terraform.tfvars"'

# Step 4: Terraform Apply using tfvars file
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'  # Adjust path if necessary
    commandOptions: '-var-file="terraform.tfvars" -auto-approve'
