trigger:
  branches:
    include:
      - main

# Define variables
variables:
  - group: 'AKS-Credentials'  # Replace with the name of your variable group
  RESOURCE_GROUP: 'my-resource-group2'
  AKS_CLUSTER_NAME: 'my-aks-cluster2'

stages:
  - stage: Deploy
    jobs:
      - job: Deploy_Prometheus_Grafana
        displayName: "Deploy Prometheus and Grafana"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UseHelmInstaller@1
            inputs:
              helmVersion: 'latest'

          - script: |
              # Login to Azure using Service Principal and set subscription context
              az login --service-principal \
                --username $(AZURE_CLIENT_ID) \
                --password $(AZURE_CLIENT_SECRET) \
                --tenant $(AZURE_TENANT_ID)

              # Set the subscription context using the subscription ID from the variable group
              az account set --subscription $(AZURE_SUBSCRIPTION_ID)

              # Get AKS credentials
              az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER_NAME)
            displayName: "Azure CLI Login, Set Subscription, and Get AKS Credentials"

          - script: |
              # Add Helm repositories
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo add grafana https://grafana.github.io/helm-charts
              helm repo update
            displayName: "Add Helm Repositories"

          - script: |
              # Create namespace if it doesn't exist
              kubectl create namespace monitoring || true
            displayName: "Cre
