adminUser: admin
adminPassword: $Perot20304050

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 10Gi
