name: Terraform GitHub Action

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Azure Login with Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true
          auth-type: 'SERVICE_PRINCIPAL'

      # Step 3: Set up Terraform (ensure at least version 1.5.0)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version_constraint: ">=1.5.0"

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="resource_group_name=myStorageResourceGroup" \
          -backend-config="storage_account_name=terracount0203" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        working-directory: terraform-project

      # Step 5: Apply Terraform Plan
      - name: Terraform Apply
        run: |
          terraform apply -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                          -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                          -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                          -auto-approve
        working-directory: terraform-project
