name: Test Azure Login

on:
  push:
    branches:
      - main

jobs:
  login-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code (optional)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using credentials from the secret
      - name: Azure Login Test
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Verify the Login (optional, just for testing)
      - name: Verify Subscription
        run: |
          az account show
