name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using individual secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      # Step 3: Set environment variables for Terraform authentication
      - name: Set environment variables
        run: |
          echo "Setting up environment variables for service principal authentication"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      # Step 4: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 5: Initialize Terraform with backend configuration
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=myStorageResourceGroup" \
            -backend-config="storage_account_name=terracount0203" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"
        working-directory: terraform-project

      # Step 6: Run Terraform Plan
      - name: Terraform Plan
        run: |
          terraform plan -var-file=env/dev.tfvars -out=tfplan
        working-directory: terraform-project

      # Step 7: Apply Terraform changes
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
        working-directory: terraform-project
